/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ejemplohilos;

import static ejemplohilos.PersonajeController.personajes;
import java.awt.BorderLayout;
import java.awt.Dimension;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author leonel
 */
public class VistaPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VistaPrincipal.class.getName());

    /**
     * Creates new form VistaPrincipal
     */
    public VistaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnIniciar = new javax.swing.JButton();
        lblMago1 = new javax.swing.JLabel();
        lblMago = new javax.swing.JLabel();
        btnGraficar = new javax.swing.JButton();
        pnlGrafica = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnIniciar.setText("Iniciar");
        btnIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarActionPerformed(evt);
            }
        });

        lblMago1.setFont(new java.awt.Font("Helvetica Neue", 0, 36)); // NOI18N
        lblMago1.setText("🧙🏼‍♂️");

        lblMago.setFont(new java.awt.Font("Helvetica Neue", 0, 36)); // NOI18N
        lblMago.setText("🧙🏼‍♂️");

        btnGraficar.setText("Graficar");
        btnGraficar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGraficarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlGraficaLayout = new javax.swing.GroupLayout(pnlGrafica);
        pnlGrafica.setLayout(pnlGraficaLayout);
        pnlGraficaLayout.setHorizontalGroup(
            pnlGraficaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 540, Short.MAX_VALUE)
        );
        pnlGraficaLayout.setVerticalGroup(
            pnlGraficaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 288, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(295, Short.MAX_VALUE)
                .addComponent(btnIniciar)
                .addGap(26, 26, 26)
                .addComponent(btnGraficar)
                .addGap(158, 158, 158))
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlGrafica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMago1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(54, 54, 54)
                    .addComponent(lblMago)
                    .addContainerGap(509, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(137, 137, 137)
                .addComponent(lblMago1)
                .addGap(44, 44, 44)
                .addComponent(pnlGrafica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIniciar)
                    .addComponent(btnGraficar))
                .addGap(16, 16, 16))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(62, 62, 62)
                    .addComponent(lblMago)
                    .addContainerGap(489, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarActionPerformed

       /* Thread hilo = new Thread (()->{
            for(int x = lblMago1.getX(); x<= this.getWidth()-100;  x+=10){
                int nuevaX = x;
                javax.swing.SwingUtilities.invokeLater(()->{
                    lblMago1.setLocation(nuevaX, lblMago1.getY());
                });
            }
            
            try{
                
                Thread.sleep(personajes[0].getEscoba().getDormirSegundos()*100);
                
                
                
            }catch(InterruptedException e){
                e.printStackTrace();
            }
        });
        
        Thread hilo2 = new Thread(()->{
            for(int x = lblMago.getX(); x<= this.getWidth()-100; x+=10){
                int nuevaX = x;
                javax.swing.SwingUtilities.invokeLater(()->{
                
                    lblMago.setLocation(nuevaX, lblMago.getY());
                });
                
                try{
                    Thread.sleep(personajes[1].getEscoba().getDormirSegundos()*100);
                }catch(InterruptedException e){
                    e.printStackTrace();
                }
            }
        }) ;
        
        hilo.start();
        hilo2.start();*/
       
       Thread hilo = new Thread(() -> {
            for (int x = lblMago.getX(); x <= this.getWidth()-100; x += 10) {
                final int nuevaX = x;

                javax.swing.SwingUtilities.invokeLater(() -> {
                    lblMago.setLocation(nuevaX, lblMago.getY());
                });

                try {
                    Thread.sleep(personajes[0].getEscoba().getDormirSegundos()*100);
                } catch (InterruptedException e) {
                    e.printStackTrace();
                }
            }
        });
        
        Thread hilo2 = new Thread(()-> {
            for(int x = lblMago1.getX(); x <= this.getWidth()-100 ; x+=10){
                final int nuevaX = x;
                
                javax.swing.SwingUtilities.invokeLater(()->{
                    lblMago1.setLocation(nuevaX, lblMago1.getY());
                });
                
                try{
                    Thread.sleep(personajes[1].getEscoba().getDormirSegundos()*100);
                }catch(InterruptedException e){
                    e.printStackTrace();
                }
                
            }
        
        });

        hilo.start();
        hilo2.start();
        
    }//GEN-LAST:event_btnIniciarActionPerformed

    private void btnGraficarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGraficarActionPerformed
        PartidaController pController = new PartidaController();
        String[][] datos = pController.datosGraficaPersonaje();
        
        DefaultCategoryDataset dataset = new DefaultCategoryDataset();
        
        for(int i=0; i<datos.length; i++){
            String nombre = datos[i][0];
            int puntos = Integer.parseInt(datos[i][1]);
            
            dataset.setValue(puntos, "Punteo Total", nombre);
        }
        
        JFreeChart grafica = ChartFactory.createBarChart(
                "Ranking de jugadores",
                "Jugadores",
                "Punteo total",
                dataset,
                PlotOrientation.VERTICAL,
                true,
                true,
                false
        );
        
        ChartPanel panel = new ChartPanel(grafica);
        
        panel.setMouseWheelEnabled(true);
        panel.setPreferredSize(new Dimension(540,288));
        
        pnlGrafica.removeAll();
        pnlGrafica.setLayout(new BorderLayout());
        pnlGrafica.add(panel, BorderLayout.CENTER);
        pnlGrafica.revalidate();
        pnlGrafica.repaint();
        
    }//GEN-LAST:event_btnGraficarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VistaPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGraficar;
    private javax.swing.JButton btnIniciar;
    private javax.swing.JLabel lblMago;
    private javax.swing.JLabel lblMago1;
    private javax.swing.JPanel pnlGrafica;
    // End of variables declaration//GEN-END:variables
}
